# Generated by Django 3.1.7 on 2021-07-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_app", "0002_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
