# Generated by Django 3.1.7 on 2021-07-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_app", "0003_employee_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
